### ISSUE TITLE
Crafting speed way to fast

### ISSUE THREAD

**Issue by sirzento** [Elvyria/MagicStorage#3]
When pressing 'craft' its impossible to craft like one. The crafting speed is already at the highest value and not like in the original where it starts slow and then it is speed up

**Comment by Elvyria** [comment]
That's a weird one. I'm already in like 20+h playthrough and i didn't have any problems with crafting speed, i'll take a look, but please recheck.

**Comment by sirzento** [comment]
Strange. I just started a new world and a new character to test it and filled the storage with stuff for testing. Maybe some other mod I was using isn't compatible. I will test it again when I got some time.
Also I did used the 64bit tmodloader version if this makes any difference.

**Comment by Elvyria** [comment]
It shouldn't be a compatibility issue with other mods and i doubt 64 bit affects it in any way, but i'm using 32bit version from Steam and singleplayer for testing. Maybe you didn't restart game after replacing original MagicStorage and it didn't unload itself fully.

**Comment by sirzento** [comment]
So after some testing it had something to do with 'Max stack +' mod. I did:
1. test with all my mods activated => crafting speed to high
2. deacticated max stack + and test it => works like it should
3. activate it again => Also works now

Idk if some cash of the "old" magicStorage survived somewhere and this caused the bug and reloading mods did the job or something else
