### ISSUE TITLE
Another mod like this

### ISSUE THREAD

**Issue by sirzento** [Elvyria/MagicStorage#4]
Hi,
I just want to inform you that another user has also forked the MagicStorage mod and has already modified many things like:
- Way more options to sort items
- Way more crafting station slots
- Support for recursive crafting (that actually works ^^)
- A quick stack and restock function

Maybe, just maybe, you two can combine forces and take the best of your and his work together :)

Here is the link: https://github.com/ExterminatorX99/MagicStorage

**Comment by Elvyria** [comment]
As of now - a bunch of good things from this fork, one way or another, found their way into an original repository of MagicStorage into 1.4 branch, with my permission to Ex, long time ago. I wasn't very active and kinda forgot, but we can close this now, i guess.

![Exterminator about MagicStorage](https://user-images.githubusercontent.com/2061234/181903248-1a605b35-8a95-4a9c-b73a-1df0589cc532.png)
